### ISSUE TITLE
The check on `rstate2` in libsmoldyn does not look consistent with the behaviour of the configuration parser

### ISSUE THREAD

**Issue by dilawar** [ssandrews/Smoldyn-official#15]
The line https://github.com/ssandrews/Smoldyn-official/blob/48d1b121794877937afa779ac8bd8e8ae9b8b9fb/source/Smoldyn/libsmoldyn.c#L1948 is currently

```
LCHECK(rstate2 >= 0 && rstate2 < MSMAX, funcname, ECbounds, "invalid rstate2");
```

Shouldn't it be 

```
LCHECK(rstate2 >= 0 && rstate2 <= MSMAX, funcname, ECbounds, "invalid rstate2");
```

Else the C-API would raise failure at the following line https://github.com/ssandrews/Smoldyn-official/blob/48d1b121794877937afa779ac8bd8e8ae9b8b9fb/examples/template.txt#L61

```
reaction back ES(front) -> E(front) + S(bsoln) K_BACK 	# dissociation reaction
```

(Not that value of `bsoln` is `MSMAX`).

Now sure if similar change is required for `rstate1`.

**Comment by ssandrews** [comment]
I agree with your proposed fix. I made the change.

-Steve
