### ISSUE TITLE
smolSetSurfaceAction does not support `new_spec` option 

### ISSUE THREAD

**Issue by dilawar** [ssandrews/Smoldyn-official#17]
https://github.com/ssandrews/Smoldyn-official/blob/48d1b121794877937afa779ac8bd8e8ae9b8b9fb/source/python/module.cpp#L566

The Python API can not support `new_spec` option unless above function supports it. The parser component `smolsurface.c`  supports it. 

In Python API, passing `new_species` (long for `new_spec`) raises `NotImplementedError`.

**Comment by ssandrews** [comment]
Issue resolved. I added a newspecies input to the smolSetSurfaceAction function in the C API and also to the SetSurfaceAction function in the Python API.

**Comment by dilawar** [comment]
Opening it because I need to make changes to the user API.
